#!/bin/bash
# Script Bash sederhana untuk mengcrack kata sandi file ZIP
#
# Dibuat oleh Rofi (Fixploit03)

# Variabel warna
m="\e[0;31m"
h="\e[0;32m"
k="\e[0;33m"
b="\e[0;34m"
c="\e[0;36m"
p="\e[0;37m"
r="\e[0m"

# Fungsi untuk mengecek root (DONE) *
function cek_root(){
	if [[ $EUID -ne 0 ]]; then
		echo -e "${p}[${m}-${p}] Script ini harus dijalankan sebagai root."
		exit 1
	fi
}

# Tentang (DONE) *
versi="v2.0"
pembuat="${h}Rofi ${p}(${h}Fixploit03${p})${r}"
github="https://github.com/fixploit03/zpct"

# Fungsi untuk mengecek sistem operasi (DONE) *
function cek_os(){
	os=$(lsb_release  -i | awk '{print $3}')
	if [[ "${os}" == "Kali" ]]; then
		:
	else
		echo -e "${p}[${m}-${p}] Script ini hanya dapat dijalankan di sistem operasi Kali Linux.${r}"
		exit 1
	fi
}

# Error handling KeyboardInterrupt (DONE) *
trap 'echo -e "\n${p}[${m}-${p}] KeyboardInterrupt${r}"; exit 1' SIGINT

# Fungsi untuk mengecek alat (DONE) * WAIT
function cek_alat(){
	daftar_alat=(
                "lsb_release"
		"combinator"
		"toggle-case"
		"john"
		"hashcat"
		"zipinfo"
		"7z"
		"unzip"
		"zip2hashcat"
		"fcrackzip"
		"bkcrack"
	)

	gagal=()

	for alat in "${daftar_alat[@]}"; do
		if ! command -v "${alat}" &>/dev/null; then
			gagal+=("${alat}")
		fi
	done

	if [[ "${#gagal[@]}" -eq 0 ]]; then
		:
	else
		echo -e "${p}[${m}-${p}] Script tidak dapat dijalankan, karena ada alat yang belum diinstal.${r}"
		echo ""
		echo -e "${p}Alat yang belum diinstal:${r}"
		echo ""
		for alat_gagal in "${gagal[@]}"; do
			echo -e "${p}- ${alat_gagal}${r}"
		done
		echo ""
		exit 1
	fi
}

# Fungsi untuk menampilkan banner script (DONE) *
function banner_script(){
	echo -e "${p}+--------------------------------------------+${r}"
	echo -e "${p}| ${c} ________  ________  ________  _________   ${p}|${r}"
	echo -e "${p}| ${c}|\_____  \|\   __  \|\   ____\|___   ___\  ${p}|${r}"
	echo -e "${p}|  ${c}\|___/  /\ \  \|\  \ \  \___\|___ \  \_|  ${p}|${r}"
	echo -e "${p}|      ${c}/  / /\ \   ____\ \  \       \ \  \   ${p}|${r}"
	echo -e "${p}|     ${c}/  /_/__\ \  \___|\ \  \____   \ \  \  ${p}|${r}"
	echo -e "${p}|    ${c}|\________\ \__\    \ \_______\  \ \__\ ${p}|${r}"
	echo -e "${p}|     ${c}\|_______|\|__|     \|_______|   \|__| ${p}|${r}"
	echo -e "${p}|                                       ${h}${versi} ${p}|${r}"
	echo -e "${p}|                       ${h}By ${pembuat} ${p}|${r}"
	echo -e "${p}|         ${h}${github} ${p}|${r}"
	echo -e "${p}+--------------------------------------------+${r}"
	echo ""
}

# Fungsi untuk memasukkan file ZIP sekaligus mengecek file ZIP (DONE) *
function masukkan_file_zip(){
	while true; do
		read -e -p $'\e[0;37m[\e[0;34m#\e[0;37m] Masukkan nama file ZIP: ' file_zip
 		file_zip=$(echo "${file_zip}" | sed -e "s/^[ \t]*//" -e "s/[ \t]*$//" -e "s/^['\"]//" -e "s/['\"]$//")
		if [[ -z "${file_zip}" ]]; then
			echo -e "${p}[${m}-${p}] Nama file ZIP tidak boleh kosong.${r}"
			continue
		else
			echo -e "${p}[${b}*${p}] Mengecek file ZIP...${r}"
			if [[ -f "${file_zip}" ]]; then
				if [[ "${file_zip##*.}" == "zip" ]]; then
					if [[ $(zipinfo -v "${file_zip}" 2>&1 | grep -i 'cannot find zipfile directory') ]]; then
						echo -e "${p}[${m}-${p}] File ZIP tidak valid atau rusak.${r}"
						continue
					else
						if [[ $(zipinfo -v "${file_zip}" 2>&1 | grep -i 'file security status: *encrypted') ]]; then
							echo -e "${p}[${h}+${p}] File ZIP ditemukan.${r}"
							break
						else
							echo -e "${p}[${m}-${p}] File ZIP tidak terenkripsi.${r}"
							continue
						fi
					fi
				else
					echo -e "${p}[${m}-${p}] File bukan file ZIP.${r}"
					continue
				fi
			else
				echo -e "${p}[${m}-${p}] File ZIP tidak ditemukan.${r}"
				continue
			fi
		fi
	done
}

# Fungsi untuk mengecek jumlah isi file ZIP (DONE) *
function cek_jumlah_isi_file_zip(){
	lebih_dari_satu=false

	jumlah_file=$(zipinfo "${file_zip}" | awk 'NR == 2 {print $9}')

	if [[ "${jumlah_file}" -gt 1 ]]; then
		status="Multi-File"
		lebih_dari_satu=true
	fi
}

# Fungsi untuk mengecek metode kompresi yang digunakan oleh file ZIP (DONE) *
function cek_metode_kompresi(){
	metode_deflate=false
	metode_store=false

	cek_metode=($(7z l -slt "${file_zip}" | grep -i 'method' | awk '{print $4}'))

	for metod in "${cek_metode[@]}"; do
		if [[ "${metod}" == "Deflate" || "${metod}" == "Deflate:Maximum" ]]; then
			metode_deflate=true
		elif [[ "${metod}" == "Store" ]]; then
			metode_store=true
		fi
	done

	if [[ "${metode_deflate}" == true && "${metode_store}" == true ]]; then
		metode="Mixed"
	elif [[ "${metode_deflate}" == true ]]; then
	    	metode="Compressed"
	elif [[ "${metode_store}" == true ]]; then
	    	metode="Uncompressed"
	fi
}

# Fungsi untuk mengecek enkripsi yang digunakan oleh file ZIP (DONE) *
function cek_enkripsi_file_zip(){
	cek_enkripsi=$(7z l -slt "${file_zip}" | grep -i 'method' | awk '{print $3}')

	if [[ $(echo "${cek_enkripsi}" | grep -o "ZipCrypto") ]]; then
		enkripsi="ZipCrypto"
	elif [[ $(echo "${cek_enkripsi}" | grep -o "AES-128") ]]; then
		enkripsi="AES-128"
	elif [[ $(echo "${cek_enkripsi}" | grep -o "AES-192") ]]; then
		enkripsi="AES-192"
	elif [[ $(echo "${cek_enkripsi}" | grep -o "AES-256") ]]; then
		enkripsi="AES-256"
	fi

	if [[ "${lebih_dari_satu}" == true ]]; then
		echo -e "${p}[${h}+${p}] Enkripsi file ZIP: ${h}${enkripsi} ${p}(${h}${metode} ${status}${p})${r}"
	else
		echo -e "${p}[${h}+${p}] Enkripsi file ZIP: ${h}${enkripsi} ${p}(${h}${metode}${p})${r}"
	fi
}

# Fungsi untuk memilih teknik crack kata sandi file ZIP (DONE) *
function pilih_teknik_crack_file_zip(){
	echo ""
	echo -e "${k}Daftar Teknik Untuk Mengcrack Kata Sandi File ZIP${p}:${r}"
	echo -e "${p}--------------------------------------------------${r}"
	echo -e "${p}[${k}1${p}] ${k}Konvensional ${p}(${k}Tanpa file Hash${p})${r}"
	echo -e "${p}[${k}2${p}] ${k}Konvensional ${p}(${k}Dengan file Hash${p})${r}"
	echo -e "${p}[${k}3${p}] ${k}KPA ${p}(${k}Known Plaintext Attack${p})${r}"
	echo ""

	while true; do
		read -p $'\e[0;37m[\e[0;34m#\e[0;37m] Pilih teknik: ' teknik_crack_file_zip

		if [[ -z "${teknik_crack_file_zip}" ]]; then
			echo -e "${p}[${m}-${p}] Teknik tidak boleh kosong.${r}"
			continue
		else
			if [[ "${teknik_crack_file_zip}" != "1" && "${teknik_crack_file_zip}" == "2" && "${teknik_crack_file_zip}" == "3" ]]; then
				echo -e "${p}[${m}-${p}] Teknik tidak tersedia.${r}"
				continue
			else
				if [[ "${teknik_crack_file_zip}" == "1" || "${teknik_crack_file_zip}" == "3" ]]; then
					if [[ "${enkripsi}" == "ZipCrypto" ]]; then
						break
					else
						echo -e "${p}[${m}-${p}] Teknik ini hanya Dapat digunakan pada file ZIP dengan enkripsi ZipCrypto (${m}PKZIP${p})${r}"
						continue
					fi
				elif [[ "${teknik_crack_file_zip}" == "2" ]]; then
					break
				else
					echo -e "${p}[${m}-${p}] Teknik tidak tersedia.${r}"
					continue
				fi
			fi
		fi
	done
}

# Fungsi untuk membuat folder untuk menyimpan file HASH file ZIP (DONE) *
function buat_folder_file_hash(){
	nama_folder_file_hash="/opt/zpct/file_hash"
	if [[ ! -d "${nama_folder_file_hash}" ]]; then
		mkdir "${nama_folder_file_hash}"
	fi
}

# Fungsi untuk memilih teknik untuk mengekstrak Hash file ZIP (DONE) *
function pilih_teknik_ekstrak_hash(){
	echo ""
	echo -e "${k}Daftar Teknik Untuk Mengekstrak Hash File ZIP${p}:${r}"
	echo -e "${p}----------------------------------------------${r}"
	echo -e "${p}[${k}1${p}] Ekstrak Hash dari salah satu isi file ZIP${r}"
	echo -e "${p}[${k}2${p}] Ekstrak Hash secara default (${k}Semua isi file ZIP${p})${r}"
	echo ""
	while true; do
		read -p $'\e[0;37m[\e[0;34m#\e[0;37m] Pilih teknik: ' teknik_ekstrak_hash
		if [[ -z "${teknik_ekstrak_hash}" ]]; then
			echo -e "${p}[${m}-${p}] Teknik tidak boleh kosong.${r}"
			continue
		else
			if [[ "${teknik_ekstrak_hash}" != "1" && "${teknik_ekstrak_hash}" != "2" ]]; then
				echo -e "${p}[${m}-${p}] Teknik tidak tersedia.${r}"
				continue
			else
				break
			fi
		fi
	done
}
# Fungsi untuk mengekstrak Hash file ZIP (DONE) *
function ekstrak_hash_file_zip(){
	nama_file_zip=$(basename "${file_zip}")
	nama_file_hash="hash_${nama_file_zip}.txt"
	path_file_hash="${nama_folder_file_hash}/${nama_file_hash}"
	real_path=$(realpath "${path_file_hash}")

	if [[ "${real_path}" == *" "* ]]; then
		real_path="'${real_path}'"
	fi

	if [[ "${teknik_ekstrak_hash}" == "1" ]]; then
		echo -e "${p}[${b}*${p}] Mengecek isi file ZIP...${r}"
		echo ""
		echo -e "${k}Daftar Isi File ZIP${p}:${r}"
		echo -e "${p}--------------------${r}"
		unzip -l "${file_zip}"
		echo ""

		lihat_isi_file_zip=$(unzip -Z1 "${file_zip}")

		while true; do
			read -p $'\e[0;37m[\e[0;34m#\e[0;37m] Masukkan salah satu nama file dari salah satu isi file ZIP: ' isi_file_zip
			if [[ -z "${isi_file_zip}" ]]; then
				echo -e "${p}[${m}-${p}] Nama file tidak boleh kosong.${r}"
				continue
			else
				if [[ $(echo "${lihat_isi_file_zip}" |  grep -x "${isi_file_zip}") ]]; then
					echo -e "${p}[${h}+${p}] File ditemukan dalam file zip.${r}"
					break
				else
					echo -e "${p}[${m}-${p}] File tidak ditemukan dalam file zip.${r}"
					continue
				fi
			fi
		done

		echo -e "${p}[${b}*${p}] Mengekstrak Hash file ZIP...${r}"

		ekstrak_hash=$(zip2hashcat -o "${isi_file_zip}" "${file_zip}" 2>&1 > "${path_file_hash}")

		if [[ $? -eq 0 ]]; then
			if [[ $(grep -o '$pkzip' "${path_file_hash}" || grep -o 'zip2' "${path_file_hash}") ]]; then
				echo -e "${p}[${h}+${p}] File Hash file ZIP berhasil diekstrak.${r}"
				echo -e "${p}[${h}+${p}] File Hash disimpan di: ${h}${real_path}${r}"
			else
				echo -e "${p}[${m}-${p}] File Hash file ZIP gagal diekstrak.${r}"
				exit 1
			fi
		else
			echo -e "${p}[${m}-${p}] File Hash file ZIP gagal diekstrak.${r}"
			exit 1
		fi
	elif [[ "${teknik_ekstrak_hash}" == "2" ]]; then
		echo -e "${p}[${b}*${p}] Mengekstrak Hash file ZIP...${r}"

		ekstrak_hash=$(zip2hashcat "${file_zip}" 2>&1 > "${path_file_hash}")

		if [[ $? -eq 0 ]]; then
			if [[ $(grep -o '$pkzip' "${path_file_hash}" || grep -o 'zip2' "${path_file_hash}") ]]; then
				echo -e "${p}[${h}+${p}] File Hash file ZIP berhasil diekstrak.${r}"
				echo -e "${p}[${h}+${p}] File Hash disimpan di: ${h}${real_path}${r}"
			else
				echo -e "${p}[${m}-${p}] File Hash file ZIP gagal diekstrak.${r}"
				exit 1
			fi
		else
			echo -e "${p}[${m}-${p}] File Hash file ZIP gagal diekstrak.${r}"
			exit 1
		fi

	fi
}

# Fungsi untuk memilih alat yang igin digunakan (DONE) *
function menu_pilih_alat(){
	echo ""
	echo -e "${k}Daftar Alat Untuk Mengcrack Hash File ZIP${p}:${r}"
	echo -e "${p}------------------------------------------${r}"
	echo -e "${p}[${k}1${p}] John The Ripper${r}"
	echo -e "${p}[${k}2${p}] Hashcat${r}"
	echo ""
	while true; do
		read -p $'\e[0;37m[\e[0;34m#\e[0;37m] Pilih alat: ' pilih_alat
		if [[ -z "${pilih_alat}" ]]; then
			echo -e "${p}[${m}-${p}] Alat tidak boleh kosong.${r}"
			continue
		else
			if [[ "${pilih_alat}" != "1" && "${pilih_alat}" != "2" ]]; then
				echo -e "${p}[${m}-${p}] Alat tidak tersedia.${r}"
				continue
			else
				break
			fi
		fi
	done
}

# Fungsi untuk memilih teknik yang ingin digunakan (DONE) *
function menu_pilih_teknik(){
	echo ""
	echo -e "${k}Daftar Teknik Untuk Mengcrack Hash File ZIP${p}:${r}"
	echo -e "${p}--------------------------------------------${r}"
	echo -e "${p}[${k}1${p}] Dictionary Attack${r}"
	echo -e "${p}[${k}2${p}] Brute Force Attack${r}"
	echo -e "${p}[${k}3${p}] Combinator Attack${r}"
	echo -e "${p}[${k}4${p}] Mask Attack${r}"
	echo -e "${p}[${k}5${p}] Prince Attack${r}"
	echo -e "${p}[${k}6${p}] Hybrid Attack${r}"
	echo -e "${p}[${k}7${p}] Subsets Attack${r}"
	echo -e "${p}[${k}8${p}] Toggle Case Attack${r}"
	echo ""
	while true; do
		read -p $'\e[0;37m[\e[0;34m#\e[0;37m] Pilih teknik: ' pilih_teknik
		if [[ -z "${pilih_teknik}" ]]; then
			echo -e "${p}[${m}-${p}] Teknik tidak boleh kosong.${r}"
			continue
		else
			if [[ "${pilih_teknik}" != "1" && "${pilih_teknik}" != "2" && "${pilih_teknik}" != "3" && "${pilih_teknik}" != "4" && "${pilih_teknik}" != "5" && "${pilih_teknik}" != "6" && "${pilih_teknik}" != "7" && "${pilih_teknik}" != "8" ]]; then
				echo -e "${p}[${m}-${p}] Teknik tidak tersedia.${r}"
				continue
			else
				break
			fi
		fi
	done
}

# Fungsi untuk memilih teknik mengcrack kata sandi file ZIP (Tanpa Hash) (DONE) *
function menu_pilih_teknik_tanpa_hash(){
	echo ""
	echo -e "${k}Daftar Teknik Untuk Mengcrack Kata Sandi File ZIP${p}:${r}"
	echo -e "${p}--------------------------------------------${r}"
	echo -e "${p}[${k}1${p}] Dictionary Attack${r}"
	echo -e "${p}[${k}2${p}] Brute Force Attack${r}"
	echo ""

	while true; do
		read -p $'\e[0;37m[\e[0;34m#\e[0;37m] Pilih teknik: ' pilih_teknik_tanpa_hash

		if [[ -z "${pilih_teknik_tanpa_hash}" ]]; then
			echo -e "${p}[${m}-${p}] Teknik tidak boleh kosong.${r}"
			continue
		else
			if [[ "${pilih_teknik_tanpa_hash}" != "1" && "${pilih_teknik_tanpa_hash}" != "2" ]]; then
				echo -e "${p}[${m}-${p}] Teknik tidak tersedia.${r}"
				continue
			else
				break
			fi
		fi
	done
}

# Fungsi untuk memasukkan file Wordlist sekaligus mengecek file Wordlist (DONE) *
function masukkan_file_wordlist(){
	while true; do
		read -e -p $'\e[0;37m[\e[0;34m#\e[0;37m] Masukkan nama file Wordlist: ' file_wordlist
		file_wordlist=$(echo "${file_wordlist}" | sed -e "s/^[ \t]*//" -e "s/[ \t]*$//" -e "s/^['\"]//" -e "s/['\"]$//")
		if [[ -z "${file_wordlist}" ]]; then
			echo -e "${p}[${m}-${p}] Nama file Wordlist tidak boleh kosong.${r}"
			continue
		else
			echo -e "${p}[${b}*${p}] Mengecek file Wordlist...${r}"
			if [[ -f "${file_wordlist}" ]]; then
				echo -e "${p}[${h}+${p}] File Wordlist ditemukan.${r}"
				break
			else
				echo -e "${p}[${m}-${p}] File Wordlist tidak ditemukan.${r}"
				continue
			fi
		fi
	done
}

# Fungsi untuk menentukan panjang kata sandi (DONE) *
function menentukan_panjang_kata_sandi(){

	# Memasukkan panjang minimal kata sandi
	while true; do
		read -p $'\e[0;37m[\e[0;34m#\e[0;37m] Masukkan panjang minimal kata sandi: ' min
		if [[ -z "${min}" ]]; then
			echo -e "${p}[${m}-${p}] Panjang minimal kata sandi tidak boleh kosong.${r}"
			continue
		else
	                if [[ "${min}" =~ ^0 ]]; then
			        echo -e "${p}[${m}-${p}] Panjang minimal kata sandi tidak boleh diawali dengan angka nol.${r}"
                	        continue
			else
				if [[ ! "${min}" =~ ^[0-9]+$ ]]; then
					echo -e "${p}[${m}-${p}] Masukkan tidak valid. Harap masukkan angka.${r}"
					continue
				else
					break
				fi

                	fi
		fi
	done

	# Memasukkan panjang maksimal kata sandi
	while true; do
		read -p $'\e[0;37m[\e[0;34m#\e[0;37m] Masukkan panjang maksimal kata sandi: ' maks
		if [[ -z "${maks}" ]]; then
			echo -e "${p}[${m}-${p}] Panjang maksimal kata sandi tidak boleh kosong.${r}"
			continue
		else
			if [[ ! "${maks}" =~ ^[0-9]+$ ]]; then
				echo -e "${p}[${m}-${p}] Masukkan tidak valid. Harap masukkan angka.${r}"
				continue
			else
				if [[ ! "${maks}" -ge "${min}" ]]; then
					echo -e "${p}[${m}-${p}] Panjang maksimal kata sandi harus lebih besar atau sama dengan panjang minimal kata sandi.${r}"
					continue
				else
					break
				fi
			fi
		fi
	done

}

# Fungi untuk menentukan pola mask (DONE) *
function menentukan_pola_mask(){
	echo ""
	echo -e "${k}Daftar Pola Mask${p}:${r}"
	echo -e "${p}-----------------${r}"
	echo -e "${p}[${k}?l${p}] Huruf kecil (${k}a-z${p})${r}"
	echo -e "${p}[${k}?u${p}] Huruf besar (${k}A-Z${p})${r}"
	echo -e "${p}[${k}?d${p}] Angka (${k}0-9${p})${r}"
	echo -e "${p}[${k}?s${p}] Simbol (${k}#-@${p})${r}"
	echo -e "${p}[${k}?a${p}] Semua karakter (${k}Huruf kecil, Huruf besar, Angka dan Simbol${p})${r}"
	echo ""

	while true; do
		read -p $'\e[0;37m[\e[0;34m#\e[0;37m] Masukkan pola mask (\e[0;33m?l?u?d?s?a\e[0;37m): ' pola_mask

		if [[ -z "${pola_mask}" ]]; then
			echo -e "${p}[${m}-${p}] Pola mask tidak boleh kosong.${r}"
			continue
		else
			if [[ ! "${pola_mask}" =~ ^(\?l|\?u|\?d|\?s|\?a)+$ ]]; then
				echo -e "${p}[${m}-${p}] Pola mask tidak valid.${r}"
				continue
			else
				break
			fi
		fi
	done
}

# Fungsi untuk menentukan kombinasi karakter (DONE) *
function menentukan_kombinasi_karakter(){
	while true; do
		read -p $'\e[0;37m[\e[0;34m#\e[0;37m] Masukkan kombinasi karakter (\e[0;33maA1$\e[0;37m): ' kombinasi
		if [[ -z "${kombinasi}" ]]; then
			echo -e "${p}[${m}-${p}] Kombinasi karakter tidak boleh kosong.${r}"
			continue
		else
			break
		fi
	done
}

# Fungsi untuk memasukkan file Wordlist ke-1 sekaligus mengecek file Wordlist ke-1 (DONE) *
function masukkan_file_wordlist_1(){
	while true; do
		read -e -p $'\e[0;37m[\e[0;34m#\e[0;37m] Masukkan nama file Wordlist ke-1: ' file_wordlist_1
		file_wordlist_1=$(echo "${file_wordlist_1}" | sed -e "s/^[ \t]*//" -e "s/[ \t]*$//" -e "s/^['\"]//" -e "s/['\"]$//")
		if [[ -z "${file_wordlist_1}" ]]; then
			echo -e "${p}[${m}-${p}] Nama file Wordlist ke-1 tidak boleh kosong.${r}"
			continue
		else
			echo -e "${p}[${b}*${p}] Mengecek file Wordlist ke-1...${r}"
			if [[ -f "${file_wordlist_1}" ]]; then
				echo -e "${p}[${h}+${p}] File Wordlist ke-1 ditemukan.${r}"
				break
			else
				echo -e "${p}[${m}-${p}] File Wordlist ke-1 tidak ditemukan.${r}"
				continue
			fi
		fi
	done
}

# Fungsi untuk memasukkan file Wordlist ke-2 sekaligus mengecek file Wordlist ke-2 (DONE) *
function masukkan_file_wordlist_2(){
	while true; do
		read -e -p $'\e[0;37m[\e[0;34m#\e[0;37m] Masukkan nama file Wordlist ke-2: ' file_wordlist_2
		file_wordlist_2=$(echo "${file_wordlist_2}" | sed -e "s/^[ \t]*//" -e "s/[ \t]*$//" -e "s/^['\"]//" -e "s/['\"]$//")
		if [[ -z "${file_wordlist_2}" ]]; then
			echo -e "${p}[${m}-${p}] Nama file Wordlist ke-2 tidak boleh kosong.${r}"
			continue
		else
			echo -e "${p}[${b}*${p}] Mengecek file Wordlist ke-2...${r}"
			if [[ -f "${file_wordlist_2}" ]]; then
				echo -e "${p}[${h}+${p}] File Wordlist ke-2 ditemukan.${r}"
				break
			else
				echo -e "${p}[${m}-${p}] File Wordlist ke-2 tidak ditemukan.${r}"
				continue
			fi
		fi
	done
}

# Fungsi untuk mencari kunci enkripsi file ZIP (DONE) *
function mencari_kunci_enkripsi_file_zip(){
	echo -e "${p}[${b}*${p}] Mengecek isi file ZIP...${r}"
	echo ""
	echo -e "${k}Daftar Isi File ZIP${p}:${r}"
	echo -e "${p}--------------------${r}"
	lihat_isi_file_zip_bkcrack=$(bkcrack -L  "${file_zip}")
	echo "${lihat_isi_file_zip_bkcrack}"
	echo ""


	while true; do
		read -p $'\e[0;37m[\e[0;34m#\e[0;37m] Masukkan salah satu nama file dari salah satu isi file ZIP yang dikompres dengan metode Store: ' isi_file_zip_bkcrack
		if [[ -z "${isi_file_zip_bkcrack}" ]]; then
			echo -e "${p}[${m}-${p}] Nama file tidak boleh kosong.${r}"
			continue
		else
			if [[ $(echo "${lihat_isi_file_zip_bkcrack}" | grep -i "${isi_file_zip_bkcrack}" | awk '{print $3}' | grep -x 'Store') ]]; then
				echo -e "${p}[${h}+${p}] File ditemukan dalam file zip.${r}"
				break
			elif [[ $(echo "${lihat_isi_file_zip_bkcrack}" | grep -i "${isi_file_zip_bkcrack}" | awk '{print $3}' | grep -x 'Deflate') ]]; then
				echo -e "${p}[${m}-${p}] File tidak dikompres dengan metode Store.${r}"
				continue
			else
				echo -e "${p}[${m}-${p}] File tidak ditemukan dalam file zip.${r}"
				continue
			fi
		fi
	done

	while true; do
		read -e -p $'\e[0;37m[\e[0;34m#\e[0;37m] Masukkan nama file Known Plaintext (\e[0;34mFile teks yang diketahui isinya\e[0;37m): ' file_plain
		file_plain=$(echo "${file_plain}" | sed -e "s/^[ \t]*//" -e "s/[ \t]*$//" -e "s/^['\"]//" -e "s/['\"]$//")

		if [[ -z "${file_plain}" ]]; then
			echo -e "${p}[${m}-${p}] Nama file Known Plaintext tidak boleh kosong.${r}"
		else
			if [[ -f "${file_plain}" ]]; then
				echo -e "${p}[${h}+${p}] File Known Plaintext ditemukan.${r}"
				break
			else
				echo -e "${p}[${m}-${p}] File Known Plaintext tidak ditemukan.${r}"
				continue
			fi
		fi
	done

	echo ""
	read -p $'\e[0;37mTekan [\e[0;32mEnter\e[0;37m] untuk memulai proses pencarian kunci enkripsi file ZIP...'
	echo ""

	tanggal=$(date +"%d-%m-%Y")
 	jam=$(date +"%H:%M:%S")
	waktu_mulai="/${tanggal}/ ${jam}"

 	echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
	echo ""
	echo -e "${p}[${b}*${p}] Mencari kunci enkripsi file ZIP...${r}"
	echo -e "${p}[${b}*${p}] Menjalankan alat Bkcrack...${r}"
	echo ""

	bkcrack -C "${file_zip}" -c "${isi_file_zip_bkcrack}" -p "${file_plain}" | tee "pot.txt"

	if [[ -f "pot.txt" ]]; then
		if [[ $(grep -o 'Found a solution' 'pot.txt') ]]; then
			kunci=$(awk 'END {print $1, $2, $3}' 'pot.txt')
			echo ""
			echo -e "${p}[${h}+${p}] Kunci enkripsi file ZIP berhasil didapatkan.${r}"
			echo -e "${p}[${h}+${p}] Kunci enkripsi file ZIP: ${h}${kunci}${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			if [[ -f "pot.txt" ]]; then
				rm "pot.txt"
			fi
		else
			echo -e "${p}[${m}-${p}] Kunci enkripsi file ZIP gagal didapatkan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			if [[ -f "pot.txt" ]]; then
				rm "pot.txt"
			fi
			exit 1
		fi
	else
		echo -e "${p}[${m}-${p}] Kunci enkripsi file ZIP gagal didapatkan.${r}"
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_selesai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
		echo ""
		exit 1
	fi
}
# Fungsi untuk memulai proses cracking (DONE) *
function start_attack(){
	echo ""
	read -p $'\e[0;37mTekan [\e[0;32mEnter\e[0;37m] untuk memulai proses cracking kata sandi file ZIP...\e[0m'
}

# Fungsi untuk membuat folder untuk menyimpan hasil cracking (DONE) *
function buat_folder_hasil(){
	nama_file_zip=$(basename "${file_zip}")
	nama_folder_hasil="/opt/zpct/hasil_cracking"

	if [[ ! -d "${nama_folder_hasil}" ]]; then
		mkdir "${nama_folder_hasil}"
	fi

	path_hasil="${nama_folder_hasil}/${nama_file_zip}.txt"
	real_path_folder_hasil=$(realpath "${path_hasil}")

	if [[ "${real_path_folder_hasil}" == *" "* ]]; then
		real_path_folder_hasil="'${real_path_folder_hasil}'"
	fi
}

function buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack(){
	real_path_file_zip=$(realpath "${file_zip}")

	if [[ "${real_path_file_zip}" == *" "* ]]; then
                real_path_file_zip="'${real_path_file_zip}'"
        fi

	nama_file_tampung="/opt/zpct/hasil_cracking/cracked.csv"

	if [[ ! -f "${nama_file_tampung}" ]]; then
		touch "${nama_file_tampung}"
		echo "File ZIP, Kata Sandi, Alat yang Digunakan, Teknik yang Digunakan, Waktu Mulai, Waktu Selesai" > "${nama_file_tampung}"
	fi

}

function run_fcrackzip(){
	menu_pilih_teknik_tanpa_hash
	alat="Fcrackzip"
	if [[ "${pilih_teknik_tanpa_hash}" == "1" ]]; then
		teknik="Dictionary Attack"
		masukkan_file_wordlist
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"

		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat Fcrackzip...${r}"
		echo ""

		fcrackzip -v -u -D -p "${file_wordlist}" "${file_zip}" | tee "pot.txt"

		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -i 'password found' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(awk 'END {print}' "pot.txt" | cut -d ' ' -f 5-)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik_tanpa_hash}" == "2" ]]; then
		teknik="Brute Force Attack"
		menentukan_panjang_kata_sandi
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"

		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat Fcrackzip...${r}"
		echo ""

		fcrackzip -v -u -b -c aA1! -l "${min}-${maks}" "${file_zip}" | tee "pot.txt"

		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -i 'password found' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(awk 'END {print}' "pot.txt" | cut -d ' ' -f 5-)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	fi
}

# Fungsi untuk menjalankan alat John The Ripper (DONE) *
function run_john_the_ripper(){
	menu_pilih_teknik
	alat="John The Ripper"
	if [[ "${pilih_teknik}" == "1" ]]; then
		teknik="Dictionary Attack"
		masukkan_file_wordlist
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat John The Ripper...${r}"
		echo ""
		john --wordlist="${file_wordlist}" --format="${format}" --pot="pot.txt" --verbosity=6 --progress-every=1 "${path_file_hash}"
		john --format="${format}" --pot="pot.txt" --show "${path_file_hash}"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "2" ]]; then
		teknik="Brute Force Attack"
		menentukan_panjang_kata_sandi
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat John The Ripper...${r}"
		echo ""
		john --incremental --min-length="${min}" --max-length="${maks}" --format="${format}" --pot="pot.txt" --verbosity=6 --progress-every=1 "${path_file_hash}"
		john --format="${format}" --pot="pot.txt" --show "${path_file_hash}"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				waktu_selesai="/${tanggal}/ ${jam}"
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi

		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "3" ]]; then
		teknik="Combinator Attack"
		masukkan_file_wordlist_1
		masukkan_file_wordlist_2
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat John The Ripper...${r}"
		echo ""
		combinator "${file_wordlist_1}" "${file_wordlist_2}" | john --stdin --format="${format}" --pot="pot.txt" --verbosity=6 --progress-every=1 "${path_file_hash}"
		john --format="${format}" --pot="pot.txt" --show "${path_file_hash}"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "4" ]]; then
		teknik="Mask Attack"
		menentukan_pola_mask
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat John The Ripper...${r}"
		echo ""
		john --mask="${pola_mask}" --format="${format}" --pot="pot.txt" --verbosity=6 --progress-every=1 "${path_file_hash}"
		john --format="${format}" --pot="pot.txt" --show "${path_file_hash}"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi

	elif [[ "${pilih_teknik}" == "5" ]]; then
		teknik="Prince Attack"
		masukkan_file_wordlist
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat John The Ripper...${r}"
		echo ""
		john --prince="${file_wordlist}" --format="${format}" --pot="pot.txt" --verbosity=6 --progress-every=1 "${path_file_hash}"
		john --format="${format}" --pot="pot.txt" --show "${path_file_hash}"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "6" ]]; then
		teknik="Hybrid Attack"
		masukkan_file_wordlist
		menentukan_pola_mask
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat John The Ripper...${r}"
		echo ""
		john --wordlist="${file_wordlist}" --mask="?w${pola_mask}" --format="${format}" --pot="pot.txt" --verbosity=6 --progress-every=1 "${path_file_hash}"
		john --format="${format}" --pot="pot.txt" --show "${path_file_hash}"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "7" ]]; then
		teknik="Subsets Attack"
		menentukan_panjang_kata_sandi
		menentukan_kombinasi_karakter
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat John The Ripper...${r}"
		echo ""
		john --subsets="${kombinasi}" --min-length="${min}" --max-length="${maks}" --format="${format}" --pot="pot.txt" --verbosity=6 --progress-every=1 "${path_file_hash}"
		john --format="${format}" --pot="pot.txt" --show "${path_file_hash}"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "8" ]]; then
		teknik="Toggle Case Attack"
		masukkan_file_wordlist
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat John The Ripper...${r}"
		echo ""
		toggle-case "${file_wordlist}" | john --stdin --format="${format}" --pot="pot.txt" --verbosity=6 --progress-every=1 "${path_file_hash}"
		john --format="${format}" --pot="pot.txt" --show "${path_file_hash}"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi

	fi
}

# Fungsi untuk menjalankan alat Hashcat (DONE) *
function run_hashcat(){
	menu_pilih_teknik
	alat="Hashcat"
	if [[ "${pilih_teknik}" == "1" ]]; then
		teknik="Dictionary Attack"
		masukkan_file_wordlist
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat Hashcat...${r}"
		echo ""
		hashcat -a 0 -m "${mode_hashcat}" "${path_file_hash}" "${file_wordlist}" --status --status-timer=1 --potfile-path "pot.txt"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "2" ]]; then
		teknik="Brute Force Attack"
		menentukan_panjang_kata_sandi
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat Hashcat...${r}"
		echo ""
		mask="?a"
		mask_pattern=$(printf "${mask}%.0s" $(seq 1 "${maks}"))
		hashcat -a 3 -m "${mode_hashcat}" "${path_file_hash}" "${mask_pattern}" --increment --increment-min="${min}" --increment-max="${maks}" --status --status-timer=1 --potfile-path "pot.txt"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "3" ]]; then
		teknik="Combinator Attack"
		masukkan_file_wordlist_1
		masukkan_file_wordlist_2
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat Hashcat...${r}"
		echo ""
		hashcat -a 1 -m "${mode_hashcat}" "${path_file_hash}" "${file_wordlist_1}" "${file_wordlist_2}" --status --status-timer=1 --potfile-path "pot.txt"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "4" ]]; then
		teknik="Mask Attack"
		menentukan_pola_mask
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat Hashcat...${r}"
		echo ""
		hashcat -a 3 -m "${mode_hashcat}" "${path_file_hash}" "${pola_mask}" --status --status-timer=1 --potfile-path "pot.txt"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "5" ]]; then
		teknik="Prince Attack"
		masukkan_file_wordlist
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat Hashcat...${r}"
		echo ""
		princeprocessor < "${file_wordlist}" | hashcat -a 0 -m "${mode_hashcat}" "${path_file_hash}" --status --status-timer=1 --potfile-path "pot.txt"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "6" ]]; then
		teknik="Hybrid Attack"
		masukkan_file_wordlist
		menentukan_pola_mask
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat Hashcat...${r}"
		echo ""
		hashcat -a 6 -m "${mode_hashcat}" "${path_file_hash}" "${file_wordlist}" "${pola_mask}" --status --status-timer=1 --potfile-path "pot.txt"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "7" ]]; then
		teknik="Subsets Attack"
		menentukan_panjang_kata_sandi
		menentukan_kombinasi_karakter
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat Hashcat...${r}"
		echo ""
		mask="?1"
		mask_pattern=$(printf "${mask}%.0s" $(seq 1 "${maks}"))
		hashcat -a 3 -m "${mode_hashcat}" "${path_file_hash}" -1 "${kombinasi}" "${mask_pattern}" --status --status-timer=1 --potfile-path "pot.txt"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi
	elif [[ "${pilih_teknik}" == "8" ]]; then
		teknik="Toggle Case Attack"
		masukkan_file_wordlist
		start_attack
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_mulai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
		echo ""
		echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
		echo -e "${p}[${b}*${p}] Menjalankan alat Hashcat...${r}"
		echo ""
		toggle-case "${file_wordlist}" | hashcat -a 0 -m "${mode_hashcat}" "${path_file_hash}" --status --status-timer=1 --potfile-path "pot.txt"
		if [[ -f "pot.txt" ]]; then
			if [[ $(grep -o ':' "pot.txt") ]]; then
				buat_folder_hasil
				kata_sandi=$(cat "pot.txt" | cut -d ':' -f 2)
				echo ""
				echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
				echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
				echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
				echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
				echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
				if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
					echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
				fi
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 0
			else
				echo ""
				echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
				tanggal=$(date +"%d-%m-%Y")
				jam=$(date +"%H:%M:%S")
				waktu_selesai="/${tanggal}/ ${jam}"
				echo ""
				echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
				echo ""
				rm "pot.txt"
				exit 1
			fi
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			exit 1
		fi

	fi
}

function run_bkcrack(){
	teknik="KPA (Known Plain Attack)"
	alat="Bkcrack"
	mencari_kunci_enkripsi_file_zip
	menentukan_panjang_kata_sandi
	start_attack
	tanggal=$(date +"%d-%m-%Y")
	jam=$(date +"%H:%M:%S")
	waktu_mulai="/${tanggal}/ ${jam}"

	echo ""
	echo -e "${p}[${b}*${p}] Dimulai pada: ${b}${waktu_mulai}${r}"
	echo ""
	echo -e "${p}[${b}*${p}] Mengcrack kata sandi file ZIP...${r}"
	echo -e "${p}[${b}*${p}] Menjalankan alat Bkcrack...${r}"
	echo ""

	bkcrack -k $kunci -b ?p -l "${min}..${maks}" | tee "pot.txt"

	if [[ -f "pot.txt" ]]; then
		if [[ $(grep -i 'password:' "pot.txt") ]]; then
			buat_folder_hasil
			kata_sandi=$(awk 'END {print}' 'pot.txt' | cut -d ' ' -f 3)
			echo ""
			echo -e "${p}[${h}+${p}] Kata sandi file ZIP ditemukan.${r}"
			echo -e "${p}[${h}+${p}] Kata sandi: ${h}${kata_sandi}${r}"
			echo "[+] File ZIP: ${file_zip}" > "${path_hasil}"
			echo "[+] Kata sandi: ${kata_sandi}" >> "${path_hasil}"
			echo -e "${p}[${h}+${p}] Hasil cracking disimpan di: ${h}${real_path_folder_hasil}${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			buat_file_untuk_menampung_file_zip_yang_berhasil_dicrack
			if [[ ! $(grep -w "${real_path_file_zip}" "${nama_file_tampung}" && grep -w "${kata_sandi}" "${nama_file_tampung}") ]]; then
				echo "${real_path_file_zip}, ${kata_sandi}, ${alat}, ${teknik}, ${waktu_mulai}, ${waktu_selesai}" >> "${nama_file_tampung}"
			fi
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			rm "pot.txt"
			exit 0
		else
			echo ""
			echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
			tanggal=$(date +"%d-%m-%Y")
			jam=$(date +"%H:%M:%S")
			waktu_selesai="/${tanggal}/ ${jam}"
			echo ""
			echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
			echo ""
			rm "pot.txt"
			exit 1
		fi
	else
		echo ""
		echo -e "${p}[${m}-${p}] Kata sandi file ZIP tidak ditemukan.${r}"
		tanggal=$(date +"%d-%m-%Y")
		jam=$(date +"%H:%M:%S")
		waktu_selesai="/${tanggal}/ ${jam}"
		echo ""
		echo -e "${p}[${b}*${p}] Selesai pada: ${b}${waktu_selesai}${r}"
		echo ""
		exit 1
	fi
}

# Fungsi untuk mengcrack file ZIP (DONE) *
function crack_file_zip(){

	# Konvensional (Tanpa Hash)
	if [[ "${teknik_crack_file_zip}" == "1" ]]; then
		run_fcrackzip
	# Konvensional (Dengan Hash)
	elif [[ "${teknik_crack_file_zip}" == "2" ]]; then
		buat_folder_file_hash
		pilih_teknik_ekstrak_hash
		ekstrak_hash_file_zip

		menu_pilih_alat

		# John The Ripper
		if [[ "${pilih_alat}" == "1" ]]; then
			if [[ $(grep -o '$pkzip' "${path_file_hash}") ]]; then
				format="PKZIP"
			elif [[ $(grep -o '$zip2' "${path_file_hash}") ]]; then
				format="ZIP"
			fi
			run_john_the_ripper
		# Hashcat
		elif [[ "${pilih_alat}" == "2" ]]; then
			if [[ "${enkripsi}" == "ZipCrypto" ]]; then
				if [[ "${lebih_dari_satu}" == true ]]; then
					if [[ "${metode}" == "Compressed" ]]; then
						mode_hashcat="17220"
					elif [[ "${metode}" == "Uncompressed" ]]; then
						mode_hashcat="17225"
					elif [[ "${metode}" == "Mixed" ]]; then
						mode_hashcat="17225"
					fi
				else
					if [[ "${metode}" == "Compressed" ]]; then
						mode_hashcat="17200"
					elif [[ "${metode}" == "Uncompressed" ]]; then
						mode_hashcat="17210"
					fi
				fi
			elif [[ "${enkripsi}" == "AES-128" || "${enkripsi}" == "AES-192" || "${enkripsi}" == "AES-256" ]]; then
				mode_hashcat="13600" # WinZip
			fi
			run_hashcat
		fi

	elif [[ "${teknik_crack_file_zip}" == "3" ]]; then
		run_bkcrack
	fi

}


# run script (DONE)
cek_root
cek_os
cek_alat
banner_script
masukkan_file_zip
cek_jumlah_isi_file_zip
cek_metode_kompresi
cek_enkripsi_file_zip
pilih_teknik_crack_file_zip
crack_file_zip

# Dibuat dengan ❤️ dan juga ☕
# Happy Cracking ^_^
